version: '3.8'

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: "bolvanka-bot"
    env_file: .env
    volumes:
      - .:/src
    ports:
      - "8080:8080"
