default_language = "ukrainian"
languages = {
    "ukrainian": {
        "chooseLang": "Виберіть будь ласка мову!",
        "returnToMain": "Повернутись до меню",
        "allFilms": "Всі Фільми",
        "reviewedFilms": "Переглянуті Фільми",
        "unreviewedFilms": "Непереглянуті Фільми",
        "addFilm": "Добавити Фільм",
        "confirm": "Підтвердити",
        "cancel": "Відмінити",
        "yes": "Так",
        "no": "Ні",
        "filmForm": "Заповнити Фільм",
        "requestOnFillFilm": "Будь ласка введіть назву фільму:",
        "noFilms": "Ви ще не зберегли жодного фільму.",
        "hi": "Привіт",
        "welcome": "Мене звуть Болванка.\nЯ допоможу вам з зберіганням переглянутих фільмів та тих, які ще хочеться переглянути.",
        "comeback": "З поверненням",
        "error": "Щось пішло не так =(",
        "name": "Назва:",
        "genre": "Жанр:",
        "mark": "Оцінка:",
        "comment": "Коментар:",
        "noSavedFilms": "Ви ще не зберегли жодного фільму",
        "fillForm": "Буль ласка заповніть форма, як показано нижче:\n",
        "example": "Назва\nЖанр\nКоментар\n",
        "note": "Введіть Назву, Жанр, Коментар в окремих повідомленнях.\n\nЗараз впишіть Назву",
        "nowAddGenre": "Зараз введіть Жанр:",
        "nowAddComment": "Зараз введіть Коментар:",
        "addTittle": "Добавити Назву",
        "addGenre": "Добавити Жанр",
        "addComment": "Добавити Коментар",
        "cancelAddingFilm": "Додавання фільму відмінено",
        "filmSaved": "Фільм збережено",
        "gotData": "Я отримав усю інформацію!\n",
        "delete": "Видалити",
        "reviewed": "Переглянуто",
        "wasDeleted": "Фільм видалено",
        "markFilm": "Оцініть фільм від 1 до 10:",
        "filmWasMarked": "Фільм позначено як 'Переглянуто' і додана оцінка"
    },
    "english": {
        "chooseLang": "Please choose a language!",
        "returnToMain": "Return to menu",
        "allFilms": "All Movies",
        "reviewedFilms": "Reviewed Movies",
        "unreviewedFilms": "Unviewed Movies",
        "addFilm": "Add Movie",
        "confirm": "Confirm",
        "cancel": "Cancel",
        "yes": "Yes",
        "no": "No",
        "filmForm": "Fill Movie",
        "requestOnFillFilm": "Please enter a movie name:",
        "noFilms": "You haven't saved any movies yet.",
        "hi": "Hi",
        "welcome": "My name is Bolvanka.\nI will help you save the movies you have watched and those you still want to watch.",
        "comeback": "Welcome back",
        "error": "Something went wrong = (",
        "name": "Name:",
        "genre": "Genre:",
        "mark": "Mark:",
        "comment": "Comment:",
        "noSavedFilms": "You haven't saved any movies yet",
        "fillForm": "Please fill out the form as shown below:\n",
        "example": "Title\nGenre\nComment\n",
        "note": "Enter Title, Genre, Comment in seperate messages.\n\nNow Enter Name",
        "nowAddGenre": "Now enter Genre:",
        "nowAddComment": "Enter comment now:",
        "addTittle": "Add Tittle",
        "addGenre": "Add Genre",
        "addComment": "Add Comment",
        "cancelAddingFilm": "Movie adding canceled",
        "filmSaved": "Movie was saved",
        "gotData": "I got all data!\n",
        "delete": "Delete",
        "reviewed": "Reviewed",
        "wasDeleted": "Movie was deleted",
        "markFilm": "Rate the movie from 1 to 10:",
        "filmWasMarked": "Film marked as 'Viewed' and rated"
    }
}
