default_language = "ukrainian"
languages = {
    "ukrainian": {
        "chooseLang": "Виберіть будь ласка мову!",
        "returnToMain": "Повернутись до меню",
        "allFilms": "Всі Фільми",
        "reviewedFilms": "Переглянуті Фільми",
        "unreviewedFilms": "Непереглянуті Фільми",
        "addFilm": "Добавити Фільм",
        "confirm": "Підтвердити",
        "cancel": "Відмінити",
        "yes": "Так",
        "no": "Ні",
        "filmForm": "Заповнити Фільм",
        "requestOnFillFilm": "Будь ласка введіть назву фільму:",
        "noFilms": "Ви ще не зберегли жодного фільму.",
        "hi": "Привіт",
        "welcome": "Мене звуть Болванка.\nЯ допоможу вам з зберіганням переглянутих фільмів та тих, які ще хочеться переглянути.",
        "comeback": "З поверненням",
        "error": "Щось пішло не так =(",
    },
    "english": {
        "chooseLang": "Please choose a language!",
        "returnToMain": "Return to menu",
        "allFilms": "All Movies",
        "reviewedFilms": "Reviewed Movies",
        "unreviewedFilms": "Unviewed Movies",
        "addFilm": "Add Movie",
        "confirm": "Confirm",
        "cancel": "Cancel",
        "yes": "Yes",
        "no": "No",
        "filmForm": "Fill Movie",
        "requestOnFillFilm": "Please enter a movie name:",
        "noFilms": "You haven't saved any movies yet.",
        "hi": "Hi",
        "welcome": "My name is Bolvanka.\nI will help you save the movies you have watched and those you still want to watch.",
        "comeback": "Welcome back",
        "error": "Something went wrong = (",
    }
}
